---
- hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks: # список тасков
  - name: Copy your flask app file to the Vagrant servers
    copy:
      src: /home/vagrant/flask/
      dest: /home/vagrant/
  - name: installing pip3
    apt:
      name: python3-pip
      update_cache: yes
  - name: Installing flask module
    pip:
      executable: pip3
      name: flask
      state: latest
  - name: run flask app
    shell: |
      nohup python3 app.py > log.txt 2>&1 &